### ISSUE TITLE
Unable to Generate Urls in the Affiliate Dashboard

### ISSUE THREAD

**Issue by joshgk00** [HotcakesCommerce/hotcakes-commerce-core#346] opened 2021-02-18 16:23 UTC
## Describe the bug
On the Affiliate Dashboard > Tools Tab, when one tries to generate any kind of url, the page refreshes and the user is not able to see the link or have a chance to copy the url to their clipboard. 

## Software Versions
- DNN:  09.08.01
- Hotcakes:  03.05.00

## To Reproduce

1. Install DNN
2. Install Hotcakes
3. Enable the affiliate program.
4. Add a new page that's visible to everyone.
5. Add the Affiliate Registration module to this new page.
6. Add a new page that's visible to at least Registered Users.
7. Add the Affiliate Dashboard module to this new page.
8. Create an API Key in Hotcakes
9. Use the API Key to create an Affiliate using the API (since the registration form currently isn't working)
10. In the Persona Bar navigate to Manage > Users
11. Set the password for the new user that was created when using the HCC API to create the Affiliate above
12. In a new browser or incognito window, log in as the user from the previous step
13. Go to the Affiliate Dashboard
14. Click on the Tools Tab
15. Try to generate any Affiliate url
16. 

## Expected behavior
When clicking on the Generate Url button, the generated link should show in the text area below and allow you to copy the link to you clipboard

## Actual behavior
The page reloads and you're taken back to the Commission Reporting Tab, the link is removed from the Tools tab

## Screenshots
https://www.screencast.com/t/TNTierSaZ6

**Comment by joshgk00** [comment] 2021-02-18 16:24
@hismightiness I have a fix for this that I am planning on contributing

**Comment by hismightiness** [comment] 2021-02-18 16:37
Awesome!  This is a duplicate of #292 though.  :)

**Comment by joshgk00** [comment] 2021-02-18 16:42
@hismightiness  It doesn't seem like a duplicate but a related issue. I don't have a fix for the Affiliate Registration form or the category drill down but a smaller fix for how a registered affiliate can generate their urls that include their affiliate id. Shouldn't it be logged as a separate issue?

**Comment by hismightiness** [comment] 2021-02-18 17:28
From the debugging I had done in the past, the same fix should fix all of them.  I'll reopen this one, just in case.  :)

**Closed** 2021-02-23 04:54 UTC
